<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Mail extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['subject', 'body', 'sended', 'e_mail_id', 'user_id', 'readed',];
    public $timestamps = false;

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function eMail()
    {
        return $this->belongsTo(EMail::class);
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::created(function (Mail $mail) {
            $user = $mail->user;
            $email = $mail->eMail;
            $folder = '';
            if ($mail->sended) {
                $idO = FolderName::where('name', 'outbox')->first()->id;
                $junked=Folder::where('folder_name_id',4)->where('user_id', $user->id)->first();
                $folder = Folder::where('folder_name_id', $idO)->where('user_id', $user->id)->first();
                $email->sended++;
            } else {
                $idI = FolderName::where('name', 'inbox')->first()->id;
                $folder = Folder::where('folder_name_id', $idI)->where('user_id', $user->id)->first();
                $email->received++;
            }
            $email->save();
            FolderMail::create([
                'mail_id' => $mail->id,
                'folder_id' => $folder->id,
                'subject' => $mail->subject,
                'e_mail' => $email->e_mail,
                'readed' => $mail->readed
            ]);
        });
    }

    public function files()
    {
        return $this->hasMany(File::class);
    }
}
