<?php

namespace App;

use function foo\func;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\Auth;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'last_name', 'first_name', 'name', 'email', 'password', 'user',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::created(function ($user) {
            $buzonE = \App\FolderName::firstOrCreate(['name' => 'Buzon de Entrada']);
            $folder = Folder::firstOrCreate([
                'folder_name_id' => $buzonE->id,
                'user_id'=>$user->id,
            ]);
        });
    }
}
